# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albioncharacter',
            name='secondary',
            field=models.CharField(choices=[('Tank', 'Tank'), ('Ranged DPS', 'Ranged DPS'), ('Melee DPS', 'Melee DPS'), ('Healer', 'Healer')], default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albioncharacter',
            name='role',
            field=models.CharField(choices=[('Tank', 'Tank'), ('Ranged DPS', 'Ranged DPS'), ('Melee DPS', 'Melee DPS'), ('Healer', 'Healer')], max_length=32),
        ),
    ]
