# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion', '0002_auto_20170809_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='building',
            field=models.CharField(choices=[('Toolmaker', 'Toolmaker'), ('Warrior', 'Warrior'), ('Mage', 'Mage'), ('Hunter', 'Hunter'), ('Alchemist', 'Alchemist'), ('Cook', 'Cook'), ('Saddler', 'Saddler')], default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='craft',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
