# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albion', '0003_auto_20170809_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='craft',
            name='tier',
        ),
        migrations.AddField(
            model_name='playercraft',
            name='craft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albion.Craft'),
        ),
        migrations.AddField(
            model_name='playercraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
