# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion', '0005_auto_20170810_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albioncharacter',
            name='id',
        ),
        migrations.AlterField(
            model_name='albioncharacter',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
