# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion', '0006_auto_20170810_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='albioncharacter',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albioncharacter',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
