# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbionCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('discord', models.CharField(max_length=32)),
                ('role', models.CharField(choices=[('Tank', 'Tank'), ('Ranged DPS', 'Ranged DPS'), ('Melee DPS', 'Melee DPS'), ('Healer', 'Healer')], max_length=32)),
                ('secondary', models.CharField(choices=[('Tank', 'Tank'), ('Ranged DPS', 'Ranged DPS'), ('Melee DPS', 'Melee DPS'), ('Healer', 'Healer')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=32)),
                ('building', models.CharField(choices=[('Toolmaker', 'Toolmaker'), ('Warrior', 'Warrior'), ('Mage', 'Mage'), ('Hunter', 'Hunter'), ('Alchemist', 'Alchemist'), ('Cook', 'Cook'), ('Saddler', 'Saddler')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albion.AlbionCharacter')),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albion.Craft')),
            ],
        ),
    ]
