# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albioncharacter',
            name='secondary',
            field=models.CharField(blank=True, choices=[('Tank', 'Tank'), ('Ranged DPS', 'Ranged DPS'), ('Melee DPS', 'Melee DPS'), ('Healer', 'Healer')], max_length=32, null=True),
        ),
    ]
